version: "3.7"
services:
  database:
    image: mongo:4.4
    ports:
      - 27019:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
      - MONGO_INITDB_USERNAME=${DATABASE_USERNAME}
      - MONGO_INITDB_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./db:/data/db
